spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blog_db?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: admin
      stat-view-servlet:
        login-username: root
        login-password: admin
#8201是druid的引用端口号
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
# 开启下划线到驼峰的自动转换, 来将数据库字段注入到对象属性
#8201是druid的引用端口号
