eureka:
  client:
    service-url:
      defaultZone: http://root:admin@node1:8100/eureka/
    healthcheck:
      enabled: true
      
spring:
  application:
    name: test

server:
  port: 9999

data:
  message: '{cipher}AQA7/P17yBkfaFhkkRTsMWOgAjx4lizL54MUZb3Qk+SQAtmAn3CSHvff/kWWX6ne32oHURc5+7jR+A3lNiUZ2rKUeoDkOMIUZG6zKNzREIPmM7bJLxGkGfValqHRnB0RuEdPmILXF43NDoU8gmiwabcUxXb0KXGOqKaOgV6Agi/EMGkisRewJz5VVE/LHtcbsTPG/4At9mzUfONtIgtozShFxLLSKu7d1StRMIuPPaCA4j88En39+gtYsVDDdzYDuEjZ5yxbcoTQFUEwMScxFVtl3nWq3TXc/Orv6Ju34LcaY1XccRK0deWa4ZG/VBovVdqat9V1nII89BbiyMS150d+Ytc5RTxFs+wOsctPAw26qq+9RupiGMjncN73/X6pDI8='
  name: 'KissShot'
